### PR TITLE
Fixed PHP Fatal error: Class 'Terminus\Models\Collections\Sites' not …

### PR DESCRIPTION
**Pull request by uberhacker**
…found in AnalyzeTableCommand.php:24 and BlobBlotterCommand.php:27

Gets this plugin working with the latest Terminus version 0.13.3.

### CODE REVIEW

**Comment by uberhacker** [comment]
Fixed this because I really like it and find it useful. :)

**Comment by alexdicianu** [comment]
@uberhacker I'm not sure this is still needed with the 1.0 update.

**Comment by uberhacker** [comment]
Right, the 1.x version will have a different namespace.  You might want to add a separate 1.x branch and create a new 0.x branch with the existing code from master.

**Comment by uberhacker** [comment]
Outdated.

**Pull request closed without merging**
